language: python
python:
  - "3.7"
before_install:
  - mv travis/travis_secrets.yaml secrets.yaml
  - mv travis/image_processing.yaml image_processing.yaml
  - sudo apt-get install -y libudev-dev ffmpeg
install:
  - pip3 install homeassistant
script:
  - hass --version
  - hass -c . --script check_config
