homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: us_customary
  # Pick timezone from here: 
  # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone
  currency: USD
  country: US
  internal_url: "http://hass.sky.net:8123"
  # Customization file
  customize: !include customize.yaml
  # External Directories Hass is allowed to access
  allowlist_external_dirs:
    - /tmp

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Enable Mobile App
#mobile_app:

# Enables System Health
system_health:

# Enable local media
media_source:

# Enable My Home Assistant
my:

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

# Intelligent Storage Acceleration
isal:

# Includes
cloud: !include cloud.yaml
sensor: !include sensor.yaml
group: !include groups.yaml
automation: !include_dir_merge_list automations/
script: !include_dir_merge_named scripts/
scene: !include scenes.yaml
switch: !include switch.yaml
template: !include template.yaml

recorder:
  purge_keep_days: 10 
  db_url: !secret db_url
  exclude:
    entities:
      - sensor.candace_phone_active_notification_count

# User Customizations

# Wemo Switches
wemo:
  static:
    - 192.168.0.31

# Person Tracking
person:
  - name: !secret person1
    id: !secret person1id
    device_trackers:
      - !secret person1device1
  - name: !secret person2
    id: !secret person2id
    device_trackers:
      - !secret person2device1

# Telegram Configuration
telegram_bot:
  - platform: polling
    api_key: !secret tapikey
    allowed_chat_ids:
      - !secret tchatid1

# Notifications
notify:
  - name: !secret bot1
    platform: telegram
    chat_id: !secret tchatid1

rest_command:
  tasker_nfc_office:
    url: !secret arofficenfc

# IFTTT
ifttt:
  key: !secret iftttkey

# Timers
timer:
  dehydrator:
  front_door_battery:
  trash:
  dogs:
  medicine:
  hvacfilter:

# Input Selects
input_select:
  living_room_tv:
    name: Living Room TV
    options:
      - Select Activity
      - Power Off
      - Watch TV
      - Watch Roku
      - PS3
    initial: Select Activity
    icon: mdi:monitor

# Input booleans
input_boolean:
  bedtime:
    name: bedtime
    initial: off
  guest:
    name: Guest Mode
    initial: off
  motion_alert:
    name: Motion Alert
    initial: on

# Input Numbers
input_number:
# Control volume for Front Entry google home
  murdok_radio:
    name: Volume
    icon: mdi:volume-high
    min: 0
    max: 1
    step: 0.05

# light:
# # Make zwave switches show as lights instead
#   - platform: switch
#     name: garage
#     entity_id: switch.garage_light_switch

#   - platform: switch
#     name: front_flood_lights
#     entity_id: switch.front_flood

#   - platform: switch
#     name: front_porch_light
#     entity_id: switch.front_porch

#   - platform: switch
#     name: front_door_entry
#     entity_id: switch.front_door_entry