homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone
  # Customization file
  customize: !include customize.yaml
  # External Directories Hass is allowed to access
  allowlist_external_dirs:
    - /tmp

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Enable Mobile App
mobile_app:

# Enables System Health
system_health:

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Workday/Holiday
binary_sensor:
  - platform: workday
    country: US
    workdays: [mon, tue, wed, thu, fri]

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

# Includes
cloud: !include cloud.yaml
sensor: !include sensor.yaml
group: !include groups.yaml
automation: !include_dir_merge_list automations/
script: !include_dir_merge_named scripts/
scene: !include scenes.yaml
switch: !include switch.yaml
image_processing: !include image_processing.yaml

zone:
  - name: Work
    latitude: !secret worklatitude
    longitude: !secret worklongitude
    icon: mdi:briefcase
  
recorder:
  purge_keep_days: 10 
  db_url: !secret db_url

# User Customizations

# Wemo Switches
wemo:
  static:
    - 192.168.0.31

# ZoneMinder
zoneminder:
  host: !secret zhost
  path_zms: /zm/cgi-bin/nph-zms
  ssl: False
  verify_ssl: False

# Cameras
camera:
  - platform: zoneminder

# Person Tracking
person:
  - name: !secret person1
    id: !secret person1id
    device_trackers:
      - !secret person1device1
  - name: !secret person2
    id: !secret person2id
    device_trackers:
      - !secret person2device1

# Telegram Configuration
telegram_bot:
  - platform: polling
    api_key: !secret tapikey
    allowed_chat_ids:
      - !secret tchatid1

# Notifications
notify:
  - name: !secret bot1
    platform: telegram
    chat_id: !secret tchatid1

rest_command:
  tasker_nfc_office:
    url: !secret arofficenfc

# Calendar
#google:
#  client_id: !secret gc_client_id
#  client_secret: !secret gc_client_secret

# IFTTT
ifttt:
  key: !secret iftttkey

# Timers
timer:
  dehydrator:
  front_door_battery:
  cimzia:
  trash:
  dogs:
  medicine:

# Input Selects
input_select:
  living_room_tv:
    name: Living Room TV
    options:
      - Select Activity
      - Power Off
      - Cable TV
      - Roku
      - PS3
    initial: Select Activity
    icon: mdi:monitor
  garage_hvac:
    name: Fanspeed
    options:
      - ""
      - "Auto"
      - "1"
      - "2"
      - "3"
      - "4"
      - "5"
      - "Quiet"
    initial: ""
    icon: mdi:fan
  frontwindow:
    name: Front Window LED
    options:
      - "Christmas"
      - "Xmas"
      - "Candy Cane"
      - "Holly Jolly"
      - "Valentine"
      - "Lovey Day"
      - "St Patty"
      - "Easter"
      - "USA"
      - "Independence"
      - "Halloween"
      - "Punkin"
      - "Thanksgiving"
      - "Turkey Day"
      - "BPM"
      - "Confetti"
      - "Cyclon Rainbow"
      - "Dots"
      - "Fire"
      - "Glitter"
      - "Juggle"
      - "Lightning"
      - "Police All"
      - "Police One"
      - "Rainbow"
      - "Rainbow with Glitter"
      - "Ripple"
      - "Sinelon"
      - "Solid"
      - "Twinkle"
    initial: "Solid"

# Input booleans
input_boolean:
  bedtime:
    name: bedtime
    initial: off
  arm_daytime:
    name: Daytime
    initial: off
  guest:
    name: Guest Mode
    initial: off
  door_open:
    name: Door Open
    initial: off
  autolock:
    name: Front Door Autolock
    initial: on
  motion_alert:
    name: Motion Alert
    initial: on
  garage_thermostat:
    name: Garage Thermostat
    initial: on
  holiday_lights:
    name: Holiday Lights
    initial: off

# Input Numbers
input_number:
  front_window_animation_speed:
    name: Front Window Animation Speed
    initial: 150
    min: 1
    max: 150
    step: 10
# Control volume for Kitchen google home
  murdok_radio:
    name: Volume
    icon: mdi:volume-high
    min: 0
    max: 1
    step: 0.05

light:
# Kitchen Light Group
  - platform: group
    name: kitchen
    entities:
      - light.pendant1
      - light.pendant2
      - light.pendant3

#MQTT Lights
mqtt:
# Front Flood Lights
  light:
    - name: "Front Flood Lights"
      state_topic: "stat/front_flood/POWER"
      command_topic: "cmnd/front_flood/POWER"
      availability_topic: "tele/front_flood/LWT"
      qos: 1
      payload_on: "ON"
      payload_off: "OFF"
      payload_available: "Online"
      payload_not_available: "Offline"
      retain: false
# Front Porch Light
    - name: "Front Porch Light"
      state_topic: "stat/front_porch/POWER"
      command_topic: "cmnd/front_porch/POWER"
      availability_topic: "tele/front_porch/LWT"
      qos: 1
      payload_on: "ON"
      payload_off: "OFF"
      payload_available: "Online"
      payload_not_available: "Offline"
      retain: false 
# Back Flood Lights
    - name: "Back Flood Lights"
      state_topic: "stat/back_flood/POWER"
      command_topic: "cmnd/back_flood/POWER"
      availability_topic: "tele/back_flood/LWT"
      qos: 1
      payload_on: "ON"
      payload_off: "OFF"
      payload_available: "Online"
      payload_not_available: "Offline"
      retain: false
# Back Porch Light
    - name: "Back Porch Light"
      state_topic: "stat/back_porch/POWER"
      command_topic: "cmnd/back_porch/POWER"
      availability_topic: "tele/back_porch/LWT"
      qos: 1
      payload_on: "ON"
      payload_off: "OFF"
      payload_available: "Online"
      payload_not_available: "Offline"
      retain: false
# Bug Zapper
    - name: "Bug Zapper"
      state_topic: "stat/bug_zapper/POWER"
      command_topic: "cmnd/bug_zapper/POWER"
      availability_topic: "tele/bug_zapper/LWT"
      qos: 1
      payload_on: "ON"
      payload_off: "OFF"
      payload_available: "Online"
      payload_not_available: "Offline"
      retain: false 
# Front Window LED
    - name: "Front Window"
      command_topic: "study/frontwindow/setpower"
      state_topic: "study/frontwindow/setpowerpub"
      rgb_state_topic: "study/frontwindow/setcolorpub"
      rgb_command_topic: "study/frontwindow/setcolor"
      brightness_state_topic: "study/frontwindow/setbrightnesspub"
      brightness_command_topic: "study/frontwindow/setbrightness"
      optimistic: false
# Zoneminder Camera Sensors
  sensor:
    - name: Front Porch
      state_topic: "zoneminder/4"
      qos: 0
      value_template: '{% if value_json.eventtype == "event_start" %} on {% else %} off {% endif %}'

    - name: Front Door
      state_topic: "zoneminder/8"
      qos: 0
      value_template: '{% if value_json.eventtype == "event_start" %} on {% else %} off {% endif %}'

# Alarm Envisalink
envisalink:
  host: !secret enhost
  panel_type: DSC
  user_name: !secret enuser
  password: !secret enpass
  code: !secret encode
  port: 4025
  evl_version: 4
  keepalive_interval: 60
  zonedump_interval: 30
  panic_type: Police
  partitions: 
    01:
      name: 'Home' 
  zones:
    01:
      name: 'Front Door'
      type: 'door'
    02:
      name: 'Back Door'
      type: 'door'
    03:
      name: 'Garage Door'
      type: 'door'
    04:
      name: 'Living Room Motion'
      type: 'motion'
    05:
      name: 'Study Window 1'
      type: 'window'
    06:
      name: 'Study Window 2'
      type: 'window'
    07:
      name: 'Dining Room Window 1'
      type: 'window'
    08:
      name: 'Dining Room Window 2'
      type: 'window'
    09:
      name: 'Dining Room Window 3'
      type: 'window'
    10:
      name: 'Back Door Window'
      type: 'window'
    11:
      name: 'Work Room Window'
      type: 'window'
    12:
      name: 'Guest Room Window'
      type: 'window'
    13:
      name: 'Master Bedroom Window 1'
      type: 'window'
    14:
      name: 'Master Bedroom Window 2'
      type: 'window'
    15:
      name: 'Master Bathroom Window'
      type: 'window'
