##########################################################
## Tensorflow
##########################################################
- platform: tensorflow
  scan_interval: 604800
  source:
    - entity_id: camera.front_porch
    - entity_id: camera.front_door
  file_out:
    - "/home/homeassistant/.homeassistant/www/{{ camera_entity.split('.')[1] }}.jpg"
  model:
    graph: /home/homeassistant/.homeassistant/tensorflow/models/efficientdet_d1_coco17_tpu-32
    categories: 
      - category: person
    area:
      left: 0.3

############################################################
## Facebox
############################################################
- platform: facebox
  scan_interval: 604800
  ip_address: !secret fbhost
  port: 8080
  source:
    - entity_id: camera.local_file
      name: facebox_front_door
