# Plex
#- name: Plex
#  platform: plex
#  host: !secret plhost
#  username: !secret pluser
#  password: !secret plpass
#  token: !secret pltoken

# Harmony Remote Living Room
- platform: template
  sensors:
    living_room:
      value_template: >-
        {% set activity = states.remote.living_room.attributes.current_activity %}
        {% if activity == 'TV' %}
          Watching TV
        {% elif activity == 'PS3' %}
          Playing PS3
        {% elif activity == 'Roku' %}
          Watching Roku
        {% elif activity == 'PowerOff' %}
          Powered Off
        {% else %}
          Unknown
        {% endif %}
      friendly_name: Living Room
      icon_template: >-
        {% if is_state('sensor.living_room', 'Watching TV') %}
          mdi:television-guide
        {% elif is_state('sensor.living_room', 'Watching Roku') %}
          mdi:plex
        {% elif is_state('sensor.living_room', 'Playing PS3') %}
          mdi:playstation
        {% elif is_state('sensor.living_room', 'Powered Off') %}
          mdi:power
        {% else %}
          mdi:television
        {% endif %}

# Front Door Lock Battery Level
- platform: template
  sensors:
    front_door_lock_battery:
      value_template: >
        {% if states('zwave.lock_front_door') != 'ready' %}
          unknown
        {% else %}
          {{ (states.zwave.lock_front_door.attributes.battery_level)|int }}
        {% endif %}
      friendly_name: 'Front Door Lock Battery'
      unit_of_measurement: '%'
      icon_template: >-
        {% set battery_level = states('sensor.front_door_lock_battery')|int('unknown') %}
        {% set battery_round = (battery_level|int / 10)|int * 10 %}
        {% if battery_level == 'unknown' %}
          mdi:battery-unknown
        {% else %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}
        {% endif %}

# Zoneminder Camera Sensors
- name: Front Porch
  platform: mqtt
  state_topic: "zoneminder/4"
  qos: 0
  value_template: '{% if value_json.eventtype == "event_start" %} on {% else %} off {% endif %}'

- name: Front Door
  platform: mqtt
  state_topic: "zoneminder/8"
  qos: 0
  value_template: '{% if value_json.eventtype == "event_start" %} on {% else %} off {% endif %}'

- platform: template
  sensors:
    front_porch_motion:
      value_template: >-
        {{ is_state('sensor.front_porch', 'on')
           or is_state('sensor.front_door', 'on') }}
      
# Flume
- platform: template
  sensors:
    flume_status:
      friendly_name: "Flume Flow Status"
      value_template: >-
        {{ states.sensor.flume_sensor.state != "0" }}
