- platform: template
  switches:
    # TV
    tv:
      friendly_name: 'TV'
      value_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'TV') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.living_room
          activity: 'TV'
      turn_off:
        service: remote.turn_on
        data:
          entity_id: remote.living_room
          activity: 'PowerOff'
    # Smart TV
    plex:
      friendly_name: 'Plex'
      value_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'Watch Smart TV') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.living_room
          activity: 'Watch Smart TV'
      turn_off:
        service: remote.turn_on
        data:
          entity_id: remote.living_room
          activity: 'PowerOff'
    # PS3
    ps3:
      friendly_name: 'PS3'
      value_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'PS3') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.living_room
          activity: 'PS3'
      turn_off:
        service: remote.turn_on
        data:
          entity_id: remote.living_room
          activity: 'PowerOff'
