- alias: Bedtime
  initial_state: on
  trigger:
    - trigger: state
      entity_id: input_boolean.bedtime
      to: "on"
  condition:
    condition: state
    entity_id: input_boolean.guest
    state: "off"
  actions:
    - action: script.turn_on
      entity_id: script.bedtime
    - delay: "00:00:05"
    - action: input_boolean.turn_off
      entity_id: input_boolean.bedtime
