# Volume control for Murdok's bedtime radio
- alias: 'Murdok Radio Volume'
  trigger:
    - platform: state
      entity_id: input_number.murdok_radio
  action:
    - service: media_player.volume_set
      data:
        entity_id: media_player.googlehome_study
        volume_level: '{{ states.input_number.murdok_radio.state }}'
