- alias: "Murdok Radio Volume Control"
  initial_state: on
  trigger:
    trigger: state
    entity_id: input_number.murdok_radio
  action:
    - action: media_player.volume_set
      data_template:
        entity_id: media_player.googlehome_living_room
        volume_level: >
          {{ states('input_number.murdok_radio') }}
