- alias: Netflix 
  initial_state: on
  trigger:
    - platform: state
      entity_id: input_boolean.netflix
      to: 'on'
  action:
    - service: script.turn_on
      entity_id: script.netflix
    - delay: '00:00:05'
    - service: input_boolean.turn_off
      entity_id: input_boolean.netflix
