- alias: Netflix
  initial_state: on
  trigger:
    - trigger: state
      entity_id: input_boolean.netflix
      to: "on"
  actions:
    - action: script.turn_on
      entity_id: script.netflix
    - delay: "00:00:05"
    - action: input_boolean.turn_off
      entity_id: input_boolean.netflix
