##########################################################
## Tensorflow
##########################################################
- platform: tensorflow
  scan_interval: 604800
  source:
    - entity_id: camera.front_porch
  file_out:
    - "/www/{{ camera_entity.split('.')[1] }}.jpg"
  model:
    graph: tensorflow/models/
    categories: 
      - category: person
